# Generated by Django 4.1.1 on 2022-11-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='descrip',
            field=models.TextField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='email',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='name',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='pnum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='title',
            field=models.TextField(max_length=1000),
        ),
    ]
