# Generated by Django 4.1.1 on 2022-11-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_mypost_descrip_alter_mypost_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
