# Generated by Django 4.1.1 on 2022-11-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mypost_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
