# Generated by Django 4.1.1 on 2022-11-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_mypost_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='pnum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
