# Generated by Django 4.1.1 on 2022-12-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_mypost_pnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
