# Generated by Django 4.1.1 on 2022-12-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
