# Generated by Django 4.1.1 on 2022-12-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('descrip_short', models.TextField(null=True)),
                ('descrip', models.TextField(null=True)),
            ],
        ),
    ]
