# Generated by Django 4.1.1 on 2022-12-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypost',
            name='district',
            field=models.TextField(null=True),
        ),
    ]
